services:
  valkey:
    image: bitnamilegacy/valkey:7.2.5-debian-12-r8
    ports:
      - '6379:6379'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
    volumes:
      - type: tmpfs
        target: /bitnamilegacy/valkey