services:
  valkey-node-0:
    image: bitnamilegacy/valkey-cluster:7.2.5-debian-12-r4
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.2
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'VALKEY_NODES=valkey-node-0'

