services:
  valkey:
    image: bitnamilegacy/valkey:7.2.5-debian-12-r8
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - type: tmpfs
        target: /bitnamilegacy/valkey